language: elixir
sudo: false
elixir:
  - 1.1.1
  - 1.2.6
  - 1.3.2
  - 1.4.0
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
  - 19.1
  - 19.2
before_script:
  - kerl list installations
notifications:
  recipients:
    - igasgeek@me.com
matrix:
  exclude:
    - otp_release: 19.0
      elixir: 1.1.1
